// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcnPgaTlYmHF99dLA4A61ajwmcRsibFAE',
    appId: '1:18275580178:web:4d6689f323faa886b11bcb',
    messagingSenderId: '18275580178',
    projectId: 'spotify-d9246',
    authDomain: 'spotify-d9246.firebaseapp.com',
    storageBucket: 'spotify-d9246.firebasestorage.app',
    measurementId: 'G-DL7EJ2DXMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1beoMrpqsMDAraESc54cr_P3nkC1eG9E',
    appId: '1:18275580178:android:024d7698d9c430ffb11bcb',
    messagingSenderId: '18275580178',
    projectId: 'spotify-d9246',
    storageBucket: 'spotify-d9246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOblEdrPjnypY1hMPAT1i5GPWjGz8MA2A',
    appId: '1:18275580178:ios:2367381a12b758feb11bcb',
    messagingSenderId: '18275580178',
    projectId: 'spotify-d9246',
    storageBucket: 'spotify-d9246.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOblEdrPjnypY1hMPAT1i5GPWjGz8MA2A',
    appId: '1:18275580178:ios:2367381a12b758feb11bcb',
    messagingSenderId: '18275580178',
    projectId: 'spotify-d9246',
    storageBucket: 'spotify-d9246.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcnPgaTlYmHF99dLA4A61ajwmcRsibFAE',
    appId: '1:18275580178:web:69d88d672379d949b11bcb',
    messagingSenderId: '18275580178',
    projectId: 'spotify-d9246',
    authDomain: 'spotify-d9246.firebaseapp.com',
    storageBucket: 'spotify-d9246.firebasestorage.app',
    measurementId: 'G-F037W3V0DP',
  );
}
